stages:
  - compile
  - package
  - infra test
  - upload
  - provision dev
  - functional tests
  - provision staging
  - accpetance tests
  - provision production
  - sanity check


jobs:
  include:
      # This job is responsible for compiling the code
    - stage: compile
      script: 
        - echo "Compiling code..."
        - echo "Generating output..."

      # This job is responsible for running the unit tests
    - stage: compile
      script: echo "Running unit tests..."

      # This job is responsible for running code inspection
    - stage: compile
      script: echo "Running code inspection..."

      # Here we move from compile stage to package stage
      # This job is responsible for packing and uploading the artifact
    - stage: package
      script: 
        - echo "Packaging application..."
        - echo "Creating server image..."

      # Here we move from package stage to infra test stage
    - stage: infra test
      script: 
        - echo "Provisioning new image..."
        - echo "Running integration tests..."

      # Here we move from infra test stage to upload artifact
    - stage: upload
      script:
        - echo "Uploading artifact..."



      # From now on we go through our CD pipeline
      # This job is responsible for provisioning the development environment
    - stage: provision dev
      script: 
        - echo "Fetching artifact..."
        - echo "Provisioning development environment..."

      # Here we move from provision dev stage to functional tests stage
      # This job is responsible for running functional tests
    - stage: functional tests
      script:
        - echo "Running functional tests..."
        - echo "Promoting artifact..."

      # Here we move from functional tests stage to provision staging stage
      # This job is responsible for running
    - stage: provision staging
      script: 
        - echo "Fetching artifact..."
        - echo "Provisioning staging environment..."

      # Here we move from provision staging stage to acceptance tests stage
      # This job is responsible for running acceptance tests
    - stage: acceptance tests
      script: 
        - echo "Running acceptance tests..."
        - echo "Promoting artifact..."
